[tasks."dev:ui"]
script = '''
cd ui
bun run dev
'''

[tasks."up"]
dependencies = ["install:sui", "install:gen", "up:ui"]

[tasks."install"]
dependencies = ["install:sui", "install:gen"]

[tasks."install:sui"]
script = '''
cargo install --git https://github.com/origin-byte/suivm
suivm use mainnet-v1.9.1
'''

[tasks."install:gen"]
script = '''
cargo install --locked --git https://github.com/kunalabs-io/sui-client-gen.git
'''

[tasks."up:ui"]
script = '''
cd ui
bun update
'''

[tasks."deploy:umi-utils"]
script = '''
cd contracts/umi-utils
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''

[tasks."deploy:sharbet"]
script = '''
cd contracts/sharbet
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''

[tasks."deploy:frostend"]
script = '''
cd contracts/frostend
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''

[tasks."deploy:frostend0"]
script = '''
cd contracts/frostend_0
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''

[tasks."gen:install"]
script = '''
cargo install --locked --git https://github.com/kunalabs-io/sui-client-gen.git
'''

[tasks."gen:sui"]
script = '''
cd ui/
rm -rf src/moveCall
sui-client-gen -m sui-client-gen.toml -o src/moveCall
bun run lint
'''
